FROM nginx:1.15.0
EXPOSE 80

COPY ./conf/default.conf /etc/nginx/conf.d/default.conf
#RUN ln -sf /dev/stdout /var/log/nginx/access.log
#RUN ln -sf /dev/stderr /var/log/nginx/error.log

CMD ["nginx", "-g", "daemon off;"]
