apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: fluentd
  labels:
    app: sample
spec:
  selector:
    matchLabels:
      app: fluentd
  template:
    metadata:
      labels:
        app: fluentd
    spec:
      containers:
        - name: fluentd
          image: vagrant_fluentd:v1.1
          securityContext:
            privileged: true
          volumeMounts:
            - name: log
              mountPath: /var/log/
            - name: var-lib-docker
              mountPath: /var/lib/docker/
              readOnly: true
      volumes:
        - name: log
          hostPath:
            path: /var/log/
            type: DirectoryOrCreate
        - name: var-lib-docker
          hostPath:
            path: /var/lib/docker/
