apiVersion: apps/v1
kind: Deployment
metadata:
  name: sample
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sample-app
  template:
    metadata:
      labels:
        app: sample-app
    spec:
      containers:
        - name: nginx
          image: vagrant_nginx:v1.1
          ports:
            - containerPort: 80
        - name: app
          image: vagrant_app:v1.1
          ports:
            - containerPort: 3000
